name: tileseteditor
description: "Yet Another TileSet Editor by qwaevisz"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+1042

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.32.0
  flame_network_assets: ^0.3.3+16
  window_manager: ^0.5.1
  file_picker: ^10.3.3
  package_info_plus: 9.0.0
  flutter_randomcolor: ^1.0.18
  image: 4.5.4
  path: 1.9.1
  url_launcher: 6.3.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
